russiandict={
    'про макс':'pro max',
    'pink':'rose',
    'пинк':'rose',
    "pm": "pro max",
    "про": "pro",
    "макс":"max",
    'мини':'mini',
    "плюс":"plus",
    "айфон":"iphone",
    "натурал":"natural",
    "белый":"white",
    "starlight":'white',
    'старлайт':'white',
    "черный":"black",
    "зеленый":"green",
    "синий":"blue",
    "голубой":"blue",
    'розовый':'rose',
    "титан":"titan",
    "желтый":"yellow",
    "+":"plus",
    "серый":"silver",
    "аирподс":"airpods",
    "air pods":'airpods',
    'usb-c':'type-c',
    'typec':'type-c',
    'тайпси':'type-c',
    '1 t':'1t',
    'пм':'pro max',
    'вотч':'watch',




}